# Generated by Django 4.1.6 on 2023-03-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discription',
            field=models.TextField(default='Discription', max_length=1000),
        ),
    ]
