# Generated by Django 4.1.6 on 2023-03-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='discription',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
